const MEANINGFUL_LOG_FILES = {
    HITS_LOG_FILENAME: "hits.log",
    IPS_LOG_FILENAME : "ips.log",
};

const MEANINGFUL_DATA_FILES = {
    HITS_DATA_FILENAME : "hits.json",
    TODAY_DATA_FILENAME: "today.json",
    WEEK_DATA_FILENAME : "week.json",
};


module.exports.MEANINGFUL_LOG_FILES = MEANINGFUL_LOG_FILES;
module.exports.MEANINGFUL_DATA_FILES = MEANINGFUL_DATA_FILES;