/**
 * DO NOT EDIT THIS FILE DIRECTLY.
 * This file is generated following the conversion of 
 * @see [./hybrid/cjs/constants.cjs]{@link ./hybrid/cjs/constants.cjs}
 * 
 **/
const CURRENT_YEAR = (new Date()).getFullYear();

export const STATS_DIR  = "stats";
export const SUB_DATA_DIR  = "data";

export const MEANINGFUL_LOG_FILES  = {
    HITS_LOG_FILENAME: `hits.log`,
};

export const LIST_DATA_FILES  = {
    IPS_REFS      : `indexers/ips.json`,
    BROWSERS_REFS : `indexers/browsers.json`,
    OS_REFS       : `indexers/oses.json`,
    ENDPOINTS_REFS: `indexers/endpoints.json`,
    LANGUAGES_REF : `indexers/languages.json`,
};

export const CHART_DATA_FILES  = {
    HITS_DATA_FILENAME     : `charts/hits.json`,
    TODAY_DATA_FILENAME    : `charts/today.json`,
    WEEK_DATA_FILENAME     : `charts/week.json`,
    YEAR_DATA_FILENAME     : `charts/${CURRENT_YEAR}-visitors.json`,
    EARNING_DATA_FILENAME  : `charts/${CURRENT_YEAR}-earning.json`,
    BROWSERS_DATA_FILENAME : `charts/browser-popularity.json`,
    OSES_DATA_FILENAME     : `charts/os-popularity.json`,
    LANGUAGES_DATA_FILENAME: `charts/language-popularity.json`,
    ENDPOINTS_DATA_FILENAME: `charts/endpoints-table.json`
};

export const CHART_TYPE  = {
    LINE : "line",
    BAR  : "bar",
    PIE  : "pie",
    TABLE: "table"
};

export const VIEW_TYPE  = {
    WEEK: "week",
    YEAR: "year"
};

export const INIT_DATA_CHART  = "{}";
export const DEFAULT_PLUGIN_PATTERN  = ".html$";













