/**
 * DO NOT EDIT THIS FILE DIRECTLY.
 * This file is generated following the conversion of 
 * @see [./lib/common.cjs]{@link ./lib/common.cjs}
 * 
 **/

// ---------------------------------------------------
// Date and Time
// ---------------------------------------------------
export const getTodayDate  = function ()
{
    let now = new Date();
    return now.toISOString().slice(0, 10);
};

export const getCurrentTime  = function ()
{
    let now = new Date();
    return now.toLocaleTimeString();
};

// ---------------------------------------------------
// Labels
// ---------------------------------------------------
export const get24HoursLabels  = function ()
{
    // Build labels
    const labels = [];
    for (let i = 0; i < 24; ++i)
    {
        labels.push(i + "h");
    }

    return labels;
};

export const getWeekLabel  = function ()
{
    return ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];
};

export const getYearLabels  = function ()
{
    return [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December"
    ];
};

// ---------------------------------------------------
// Utils
// ---------------------------------------------------
export const getYearFilename  = () =>
{
    return (new Date()).getFullYear() + ".json";
};

export const fakeIp  = () =>
{
    return (Math.floor(Math.random() * 255) + 1) + "." + (Math.floor(Math.random() * 255)) + "." + (Math.floor(Math.random() * 255)) + "." + (Math.floor(Math.random() * 255));
};


// Date and Time strings



// Labels







