/**
 * DO NOT EDIT THIS FILE DIRECTLY.
 * This file is generated following the conversion of 
 * @see [./constants.cjs]{@link ./constants.cjs}
 * 
 **/

export const MEANINGFUL_LOG_FILES  = {
    HITS_LOG_PATH: "hits.log",
    IPS_LOG_PATH: "ips.log",
};

export const MEANINGFUL_DATA_FILES  = {
    HITS_DATA_PATH: "hits.json",
    TODAY_DATA_PATH: "today.json",
    WEEK_DATA_PATH: "week.json",
    YEAR_DATA_PATH: "year.json",
};



