/**
 * DO NOT EDIT THIS FILE DIRECTLY.
 * This file is generated following the conversion of 
 * @see [./constants.cjs]{@link ./constants.cjs}
 * 
 **/
export const MEANINGFUL_LOG_FILES  = {
    HITS_LOG_FILENAME: "hits.log",
};

export const LIST_DATA_FILES  = {
    IPS_REFS      : "indexers/ips.json",
    BROWSERS_REFS : "indexers/browsers.json",
    OS_REFS       : "indexers/oses.json",
    ENDPOINTS_REFS: "indexers/endpoints.json",
    LANGUAGES_REF : "indexers/languages.json",
};

export const CHART_DATA_FILES  = {
    HITS_DATA_FILENAME     : "charts/hits.json",
    TODAY_DATA_FILENAME    : "charts/today.json",
    WEEK_DATA_FILENAME     : "charts/week.json",
    MONEY_DATA_FILENAME    : "charts/money.json",
    BROWSERS_DATA_FILENAME : "charts/browser-popularity.json",
    OSES_DATA_FILENAME     : "charts/os-popularity.json",
    LANGUAGES_DATA_FILENAME: "charts/language-popularity.json",
    ENDPOINTS_DATA_FILENAME: "charts/endpoints-table.json"
};

export const CHART_TYPE  = {
    LINE : "line",
    BAR  : "bar",
    PIE  : "pie",
    TABLE: "table"
};

export const INIT_DATA_CHART  = "{}";









