/**
 * DO NOT EDIT THIS FILE DIRECTLY.
 * This file is generated following the conversion of 
 * @see [./constants.cjs]{@link ./constants.cjs}
 * 
 **/
export const MEANINGFUL_LOG_FILES  = {
    HITS_LOG_FILENAME: "hits.log",
    IPS_LOG_FILENAME : "ips.log",
};

export const MEANINGFUL_DATA_FILES  = {
    HITS_DATA_FILENAME : "hits.json",
    TODAY_DATA_FILENAME: "today.json",
    WEEK_DATA_FILENAME : "week.json",
};



